/* eslint-disable */
/* This file is auto-generated by scripts/generate-image-manifest.mjs. */

export const STOCK_IMAGES: string[] = [
  "/images/stock/back-view-hands-with-gloves-drawing-with-marker.jpg",
  "/images/stock/beautiful-woman-measures-waist-number-black-lingerie-by-blue-measuring-device-narrow-waist-thin-long-legs-sport-diets-loss-weight.jpg",
  "/images/stock/bikini-bottoms-are-designed-look-like-they-have-been-surgically-removed.jpg",
  "/images/stock/close-up-slim-woman-with-vitiligo-skin.jpg",
  "/images/stock/cropped-black-woman-underwear-showing-buttocks.jpg",
  "/images/stock/cryolipolysis-hardware-cosmetology-body-care-non-surgical-sculptures-body.jpg",
  "/images/stock/doctor-measuring-woman-waist.jpg",
  "/images/stock/female-body-with-drawing-arrows-abdomen-liposuction-cellulite-removal.jpg",
  "/images/stock/femine-beauty-lines-concept-with-slim-woman.jpg",
  "/images/stock/fit-man-holding-measuring-tape-around-waist.jpg",
  "/images/stock/lifting-tightening-concept-young-lady-white-top-panties-posing-with-massage-lines-arrows-her-body.jpg",
  "/images/stock/loose-weight-concept-woman-with-regular-normal-body.jpg",
  "/images/stock/overweight-young-man-with-measuring-tape-home.jpg",
  "/images/stock/unrecognizable-young-woman-pinching-her-inner-thigh-examining-cellulite.jpg",
  "/images/stock/woman-pinched-her-fat-body.jpg",
  "/images/stock/young-man-checking-out-his-weight-isolated-white-wall.jpg"
];

export const BEFORE_AFTER_IMAGES: string[] = [
  "/images/before-after/result-1.jpg",
  "/images/before-after/result-2.jpg",
  "/images/before-after/result-3.jpg",
  "/images/before-after/result-4.jpg",
  "/images/before-after/result-5.jpg",
  "/images/before-after/result-6.jpg"
];

